### ISSUE TITLE
callFirestore with serverTimestamp has unexpected results

### ISSUE THREAD

**Issue by james-dowell** [prescottprue/cypress-firebase#132]
Hi @prescottprue, 

Using the following command to set an object with a timestamp property i.e.:

```
cy.callFirestore(
    'set',
    `buildings/${BUILDING_ID}/parcels/${TEST_PARCEL_ID}`,
    {
        timeOfArrival: firestore.FieldValue.serverTimestamp(),
    }
);
```

Results in:

```
{
    timeOfArrival: { _methodName: 'FieldValue.serverTimestamp' } (string)
} (Map)
```

I've done a bit of investigating and it looks like there's possibly a know issue with cy.task stringifying and parsing the data which could be related:

[https://github.com/cypress-io/cypress/issues/4980](https://github.com/cypress-io/cypress/issues/4980)

Is there anything with the library that would help with or is it possible to work around the issue somehow?

I've crudely messed around in the tasks.js and got it working for my example but it's not something good enough to be a fix but I thought I'd include it incase it was useful:

```
    if (action === 'set') {
        Object.keys(data).forEach(key => {
            if (data[key] && data[key]._methodName && data[key]._methodName === 'FieldValue.serverTimestamp') {
                data[key] = adminInstance.firestore.FieldValue.serverTimestamp()
            }
        })
        return adminInstance
            .firestore()
            .doc(actionPath)[action](data, (options === null || options === void 0 ? void 0 : options.merge) ? { merge: options === null || options === void 0 ? void 0 : options.merge } : undefined)
            .catch(handleError);
    }
```

Let me know if I can provide anything more useful! Thanks in advance for any help and for the lib!

**Comment by prescottprue** [comment]
Yeah, I have bumped into this one before and that was the thought around the `withMeta` option, but that only does `createdAt` and `createdBy`.  Ideally it would allow service timestamps on any param like what you have shown.

Thanks for posting your solution! That is actually really similar to what I was thinking, but we would hopefully have it also handle multiple levels deep

**Comment by james-dowell** [comment]
I could take a stab at a PR for something a bit more robust with a test that could handle deeply nested timestamps if you'd like? .. probably in the next day or two. Unless you've already got it covered of course 😀

**Comment by prescottprue** [comment]
@james-dowell That would be amazing if you get the chance, thanks!

**Comment by prescottprue** [comment]
The current solution we are using is causing the following error:

![image](https://user-images.githubusercontent.com/2992224/82347213-5ad90300-99c5-11ea-84a2-77d0120a077d.png)


This is because we are actually using firebase-admin in the plugin code instead of using the timestamp passed from the adminInstance - this is needed to handle how things are done in the Cypress environment and is actually the reason that the admin instance needs to be passed to begin with. firebase-admin should only be getting used for types instead of required

**Comment by prescottprue** [comment]
Pushed up a change to the v1.3.0 branch that should fix the issue - going to wait until I can do a bit more testing before merging

**Comment by james-dowell** [comment]
Ahh I see okay 👍 sounds good. Thanks for pushing this through @prescottprue , much appreciated.

Let me know if I can help out with anything else

**Comment by aziparu** [comment]
Hi @james-dowell. Thanks to you and @prescottprue for writing the changes to allow for server timestamps. I started using v1.3.0 and things are working fine so far. I was wondering if you could help me with something. I'm not able to use `firestore.FieldValue.serverTimestamp()` as you did in your example in the OP. If I add `import { firestore } from 'firebase-admin';`, then I get this error in the Cypress browser:
```
Error: Webpack Compilation Error
./node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/operationsClient.js
Module not found: Error: Can't resolve './operations_client_config'
```
If I add `import { firestore } from 'firebase';` instead, then I get this error during the test run:
```
CypressError
cy.task('callFirestore') failed with the following error:
> Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'Ca' closes the circle
```
Right now, I'm using `{ _methodName: 'FieldValue.serverTimestamp' }` instead of `firestore.FieldValue.serverTimestamp()`, which works. Any help would be appreciated.

**Comment by prescottprue** [comment]
@aziparu The admin SDK can not be loaded within Cypress since it is running within the browser environment. The reason that most of this logic has lived within custom tasks is that those live within the node environment and are called from the cypress test environment through the provided custom commands.

**Comment by aziparu** [comment]
I see. That makes sense. Do you know how can I set a serverTimestamp on a field using `cy.callFirestore` like 
```
cy.callFirestore('set', 'path/to/doc`, { 
  name: 'Apples',
  lastUpdated: firestore.FieldValue.serverTimestamp() 
});
```
aside from using `{ _methodName: 'FieldValue.serverTimestamp' }` instead of `firestore.FieldValue.serverTimestamp()`?

**Comment by prescottprue** [comment]
@aziparu You should be able to pull that in from the client Firebase SDK:

```js
import firebase from 'firebase/app'
import 'firebase/firestore'

// Then later
firebase.firestore.FieldValue.serverTimestamp()
```

**Comment by prescottprue** [comment]
Going to wait to close this until it is better documented, but [v1.3.0](https://github.com/prescottprue/cypress-firebase/releases/tag/v1.3.0) with the noted changes has been released

**Comment by prescottprue** [comment]
Logic has been improved for Timestamps which are not serverTimestamp, and docs have been added.

@aziparu I have actually now started using `firebase.firestore.Timestamp.now()` for server timestamps, or `firebase.firestore.Timestamp.fromDate(new Date('01/01/2020'))` when specifying a specific date.

If you really still want to be setting a timestamp, you can do `{ _methodName: 'FieldValue.serverTimestamp' }`, but as you mentioned that is a bit unclear. We will probably want to come up with a better way to detect this for serverTimestamps, but normal timestamps seem to be working well now.
