### ISSUE TITLE
Your API key is invalid, please check you have copied it correctly

### ISSUE THREAD

**Issue by JDansercoer** [prescottprue/cypress-firebase#136]
I tried to follow along the Readme, and got the first few steps working. I can confirm that my integration works, since the firestore document example is working.

However, when I try to add `cy.login()` to my test hooks, I get this error
![image](https://user-images.githubusercontent.com/11869830/83071746-e6a9f980-a06d-11ea-83ef-b272ea7b7e94.png)

This is my test file.

```
describe('Hooks', () => {
  before(() => {
    cy.login();
  });

  it('Runs', () => {
    cy.viewport('iphone-x');
    cy.visit('https://dev.estockx.com/');
  });
});
```

I have tried all three methods of adding the userId as explained in the readme, but none seem to work.

What am I missing?

**Comment by prescottprue** [comment]
It seems like the firebase instance being initialized within test is not finding the API key - the Firestore example working could be because of the tasks making the connection through the settings you passed, but this is different than the login command which connects directly with the Client SDK which needs to be passed the API key. Are you able to share your code so that I can try to reproduce?

Do you have the API key hard coded [like in the basic example](https://github.com/prescottprue/cypress-firebase/blob/master/examples/basic/cypress/support/commands.js#L9) or are you loading it from an environment variable in Cypress? If the second, have you logged to confirm the value is coming into the environment as you expect?

**Comment by JDansercoer** [comment]
I am terribly sorry. Seems I should have gone to bed last night instead of the late night coding session.

I never added the `fbConfig` in `commands.js`.

My apologies, and thanks for this great library!

**Comment by prescottprue** [comment]
No problem at all, glad to hear you got it working!

**Comment by silvanm** [comment]
Your mistake is my luck, @JDansercoer - I made the exact same error. And this thread helped me fix it. 😄
