### ISSUE TITLE
Error GCLOUD_PROJECT environment variable

### ISSUE THREAD

**Issue by sandeep-bastola** [prescottprue/cypress-firebase#225]
I followed the steps until 11, but got the following error upon running npx cypress open command. 

Error GCLOUD_PROJECT environment variable or project_id from service account to initialize Firebase.

Localhost is running properly.

Any help would be highly appreciated.

**Comment by prescottprue** [comment]
Thanks for reaching out! Is this in your local environment or in CI that you are having the issue? When you say localhost is running properly I'm guess you mean the dev server for your app?

If you are able to share the project I should be able to help debug further

**Comment by sdedieu** [comment]
Hi,

I have the same issue using cypress in a Vue CLI project (but I don't think this last point is relevent).

I get :
Error: Error GCLOUD_PROJECT environment variable or project_id from service account to initialize Firebase.
running the "npm run test:e2e" command which run the "vue-cli-service test:e2e" command which run the cypress open.

I believe this error occurs because the support/commands.js script is read after the plugins/index.js script. 
And the cypressFirebasePlugin(on, config, admin) line is called with an admin object without any apps (adminInstance.apps.length === 0).

Placing some "console.log" commands in the support/commands.js and plugins/index.js files indicates me that those in the plugins/index.js are displayed but none of the support/commands.js.

**Comment by junkycoder** [comment]
Had same error on `cypress open`. Seems like command initialization is separated from plugin configuration.
You just need to add `admin.initializeApp` before you register the plugin to fix it.

```
const fbConfig = {
  // Your config from Firebase Console
};

module.exports = (on, config) => {
  admin.initializeApp(fbConfig); // <- HERE
  const extendedConfig = cypressFirebasePlugin(on, config, admin);

  // Add other plugins/tasks such as code coverage here

  return extendedConfig;
};
```

**Comment by prescottprue** [comment]
Closing since a repro wasn't provided
