### ISSUE TITLE
Issue related callable functions

### ISSUE THREAD

**Issue by zvartb** [prescottprue/cypress-firebase#316]
Hello,

I am trying to create a test. 
Result is pass, when I run it in open mode, but when I run it from command line, it was failed.
The issue appears, when we use firebase callable functions.

Please see the error message in the attached screenshot:
![image](https://user-images.githubusercontent.com/77267226/112126822-41ed3f80-8bde-11eb-887b-29e622151848.png)

Is there way to solve that problem?

Thanks,

**Comment by prescottprue** [comment]
The issue seems to be the service worker failing to register - this service work is often used to give Firebase Cloud Messaging capability. Also seems like there is an issue parsing that file (since it is js, not HTML).

Not sure how this would relate to callable functions or to cypress-firebase? Are you able to provide an example repo where the issue can be reproduced?
