### ISSUE TITLE
window.fbInstance undefined on Cypress test runner

### ISSUE THREAD

**Issue by travwritescode** [prescottprue/cypress-firebase#45]
The application I am currently trying to test is built on auth0 for authentication and uses a Firestore backend. Auth0 authentication is done completely separately from anything relating to Firestore, so first we do that and it is working fine. 

Using cypress-firebase we are able to seed data in the Firestore instance using the custom commands `cy.callFirestore()` and all methods work including delete. In the process of running the tests though, and after some troubleshooting, we have found out that `window.fbInstance` is undefined. So the Firestore instance we have set up is never attached to the window so the application under test never gets connected to it. Our `configure-store.js` is set up the same way as your gist [here](https://gist.github.com/prescottprue/329dc74dda512dd496b75e710707fc4d) too.

Currently, I am not using `cy.login()` in my tests, but that does not seem like the solution to this problem. It has it's own problem when using `cy.login()` though where I get an error message saying the API key is invalid, but is the same from the FIrestore instance.

@prescottprue do you have an example application of all of this working with a Firestore backend?

**Comment by prescottprue** [comment]
The actions called through cypress-firebase including `cy.callFirestore` actually use firebase-tools instead of the current user's auth (which is handled by `cy.login`). This is because you will most likely want to be seeding/verifying data in a way which will not adhere to security rules for the client, that means you must have a service account or token for the CLI to use.

Do you have a `cypress.env.json` or call `cypress-firebase createTestEnv` before running your tests? It creates a `cypress.env.json` which contains a JWT that is created by calling firebase through firebase-tools (which requires either a service account or a CI token). `cy.login` generated JWT to login.

The [tests in fireadmin use Firestore including `cy.callFirestore`](https://github.com/prescottprue/fireadmin/blob/master/cypress/integration/Project/ActionRunner.spec.js), so those may be a good reference.

**Comment by prescottprue** [comment]
The actions called through cypress-firebase incluidng `cy.callFirestore` actually use firebase-tools instead of the current user's auth (which is handled by `cy.login`). This is because you will most likley want to be seeding/verifying data in a way which will not adhere to security rules for the client, that means you must have a service account or token for the CLI to use.

Do you have a `cypress.env.json` or call `cypress-firebase createTestEnv` before running your tests? It creates a `cypress.env.json` which contains a JWT that is created by calling firebase through firebase-tools (which requires either a service account or a CI token). `cy.login` generated JWT to login.

The [tests in fireadmin use Firestore including `cy.callFirestore`](https://github.com/prescottprue/fireadmin/blob/master/cypress/integration/Project/ActionRunner.spec.js), so those may be a good reference. That said,

**Comment by travwritescode** [comment]
I have a `cypress.env.json` and I call `cypress-firebase createTestEnv` before running tests. If `cy.login()` handles the user's auth for the current user then maybe that is the missing piece.

When calling `cy.login()` in a before hook on my tests, the before hook fails and when I print the message to the console in the Cypress runner, I see the error: `Error: Your API key is invalid, please check you have copied it correctly.` The API key which is set in `cypress/config.json` is already successfully used to seed and clean up our Firestore database. Where is this error coming from? It would be helpful to see where exactly the error is being thrown so I could diagnose the issue.

**Comment by prescottprue** [comment]
The API key that is used from `cypress/config.json` is for the front end sdk, so if you have provided a CI token (can be used to auth for seeding/verifying database in place of a service account). As [shown in the setup section](https://github.com/prescottprue/cypress-firebase#setup), the config gets passed to `firebase.initializeApp` inside of your cypress commands file - this is most likley where the error is being thrown. This would be the API key from the Firebase console, not from running `firebase login:ci`. Hope this clarifies?

Something else to note: If you CLI is already authed, adding a token for verifying/seeding may not be needed

**Comment by travwritescode** [comment]
After further investigating, it appears fbInstance was successfully assigned to _a_ window, just not _the_ window we need it to be assigned to. In Chrome dev tools console in the Cypress runner window, it looks like there are 3 context layers: application - Cypress - spec. 

![image](https://user-images.githubusercontent.com/15748191/63379635-f31c5b80-c351-11e9-8323-7f2bf2fa34b5.png)

Executing `window.fbInstance` on the app context and the Cypress context yields `undefined`, while doing the same on spec context yields the fbInstance object as expected. So the app itself is not connected to a firebase instance and therefore isn't loading any of the data we need. Is this the same behavior in your experience?

**Comment by prescottprue** [comment]
I don't believe we have experienced this issue yet and have been able to authenticate correctly - let me try to replicate and see if I am maybe missing something

**Comment by jwbaart** [comment]
@travwritescode did you manage to fix this issue? I'm encountering the same issue.

**Comment by prescottprue** [comment]
This was also reported in #84 - I still haven't been able to reproduce in any of my applications, so if someone could provide a repo where this can be reproduced, that would be awesome. Would really love to figure out the cause of this one

**Comment by jwbaart** [comment]
Thank you for the effort, really appreciate it.

I 'happen to have' an example repo, namely my repo of the original thread :)
[Link to repo](https://github.com/jwbaart/quotes)

**Comment by jwbaart** [comment]
@prescottprue managed to reproduce the issue?

**Comment by prescottprue** [comment]
I have reproduced - it actually seems like you don't need to look for the shared instance at all. The initialized Firebase instance passed into Cypress ends up being shared with the instance initialized within the app. I am planning on updating the docs, but is this what you are seeing?

So if you try to call `cy.login` you receive an error? What is the wording exactly?

**Comment by prescottprue** [comment]
Usage of window has been removed from the setup since it apparently isn't needed - are you still experiencing the error?

**Comment by jwbaart** [comment]
Sounds good, I'll try it this weekend and let you know!

**Comment by jwbaart** [comment]
If I ignore the window.fbInstance issue then the cy.login() seems to successful:
`cy.login().then((result) => console.log(result)); \\ logs an auth object`
The auth object contains the correct test email, firebase project id and uid so I assumes it's valid. My (simplified) auth service show the following:
`this._authState.subscribe(authUser => console.log('authUser', authUser)); // logs null`
And doesn't receive an auth object.

So cy has a valid auth object but the authservice of angularfire only registers a non logged in user.  Time for some more debugging!

**Comment by prescottprue** [comment]
Thanks to all for reporting! Usage of window is no longer part of the setup. If this is still being experienced could we open a new issue with a repro of this not working with angularfire
