### ISSUE TITLE
Firebase functions unaware of changes in admin used by cypress

### ISSUE THREAD

**Issue by AdrianLsk** [prescottprue/cypress-firebase#456]
I am trying to test my api which uses firebase functions and hence firebase admin. I am using emulators.

I created a simple task (similarly like the native createCustomToken does in this library) to set user's attribute emailVerified to true, which is then used by the api.

When running the task in cypress, I can see that the emailVerified is set correctly, using getAuthUser.

But the admin instance from the api in firebase-functions is not aware of the change and the call fails.

Any idea why this happens? Both admin instances should be connected to emulators, right?

Also, when signing with cypress login function, the runner calls google api instead of the emulator. 

cypress.env.json
```
{
  "GCLOUD_PROJECT": "test",
  "FIREBASE_AUTH_EMULATOR_HOST": "127.0.0.1:9999",
  "FIRESTORE_EMULATOR_HOST": "127.0.0.1:8088",
  "FIREBASE_STORAGE_EMULATOR_HOST": "127.0.0.1:9199"
}
```
system env variables
```
GCLOUD_PROJECT=test
SERVICE_ACCOUNT=./functions/serviceAccount.json
FIREBASE_AUTH_EMULATOR_HOST=127.0.0.1:9099
FIRESTORE_EMULATOR_HOST=127.0.0.1:8088
FIREBASE_STORAGE_EMULATOR_HOST=127.0.0.1:9199
```

I am using firebase emulators inside my dev app and have also set up the emulators in the cypress commands.js file.
The app is started using firebase emulators exec and then cypress is run/open in separate terminal with cypress command.

**Comment by prescottprue** [comment]
Are you sure that you logged out and back in after changing the custom claims of the user? Custom claims are part of the auth token, which will only update after reauthenticating - it is not real time like RTDB/Firestore

getAuthUser will return the value within Firebase Auth's backend, not the value of the current auth token (again, you need to log out and back in after changing custom claims in order to get the updated value)

I would say you make sure to update your auth user with that custom claim before logging is, so that you know your token will have that


Going to close assuming that was the issue, please let me know either way - if it isn't the case we can reopen
