### ISSUE TITLE
bug(firestore): nested Timestamp value not persisting

### ISSUE THREAD

**Issue by yellowee** [prescottprue/cypress-firebase#740]
**Describe the bug**

I have a problem inserting a timestamp that is nested deep in the structure. Is the library serializing objects before the insert please?

**To Reproduce**

Create an object as follows:

```
const time = Timestamp.fromDate(new Date())
cy.callFirestore('set', 'test/foo', { elo: [{ time }] })
```

**Expected behavior/code**
I would expect the time keey to be a timestamp value, but in fact it is a `map` with nanoseconds and secons

**Additional Context/Screenshots**

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/24992893/209471321-2029a528-ae62-4b01-85eb-5c13ec65f1f4.png">

**Comment by prescottprue** [comment]
Just want to confirm - was this with [v2.2.3](https://github.com/prescottprue/cypress-firebase/releases/tag/v2.2.3)? There was a fix in that version for nested timestamp values. There is a test confirming that, so if things still aren't working we will want to adjust the test to cover that

Yes there is serialization because the request has to go from the browser to the NodeJS side so that firebase-admin can be used to call the DB (admin access instead of user). Part of that process is marking timestamps in a way that they can be parsed again on the node side

**Comment by prescottprue** [comment]
@yellowee I just ran the code you provided in the typescript example with v2.2.3 and it is working as expected:
![image](https://user-images.githubusercontent.com/2992224/210115886-c22c4090-5902-43a6-bb9c-dede41941045.png)

Could you give the newest version a try? Let me know either way, if that doesn't fix it we can reopen

**Comment by yellowee** [comment]
Hey, the problem is indeed resolved by the newest version. Thank you!
