### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by jwbaart** [prescottprue/cypress-firebase#84]
I'm trying to setup a firebase cypress test but after following the readme I'm getting the following error:

> Error: Your API key is invalid, please check you have copied it correctly.

I copied and paste the value of the 'apiKey' property of the firebase project multiple times so I should be using the correct key. Would you happen to have any other insights into what's going on?

**Comment by prescottprue** [comment]
It is referencing the API key which is being injected within your `cypress.env.json` - you have to make sure that this matches your API key for initializing the front end Firebase SDK.

**Comment by jwbaart** [comment]
Found it, missed the following in the readme:
> // Your config from Firebase Console
So the API key error is gone!

Next issue, the cy.login() is executed but the onAuthStateChanged in my app only picks up an auth change with null value. When logging the auth in your login function, see [here](https://github.com/prescottprue/cypress-firebase/blob/master/src/attachCustomCommands.ts#L138), a auth object is visible.

**Comment by prescottprue** [comment]
This should be better documented, but have you initialized the Firebase SDK within your test utils and set the instance to the window? Then use that instance within your app?

Here is an example of where I do this in the fireadmin tests:
* [initialize sdk within tests](https://github.com/prescottprue/fireadmin/blob/master/cypress/support/commands.js#L13-L28)
* [Skipping init if instance exists on window](https://github.com/prescottprue/fireadmin/blob/master/cypress/support/commands.js#L13-L28)
* [Using the initialized instance](https://github.com/prescottprue/fireadmin/blob/master/src/store/createStore.js#L82-L83)

**Comment by jwbaart** [comment]
Thanks for your quick reply!

I copied and paste the command.js excerpt from the readme. Setting the instance to the window was missing so I added it, to no avail :-(
This is my [command.js](https://github.com/jwbaart/quotes/blob/feature/cypress-e2e/cypress/integration/quote/add.spec.js).

**Comment by prescottprue** [comment]
@jwbaart Did you also use that instance from the window in your application if it exists? It seems like from the looks of [your app module](https://github.com/jwbaart/quotes/blob/8a36ec1a876eecc9d2a9acd9fab4890990a54a29/src/app/app.module.ts#L29), that you aren't, but not sure.

I have seen the window.fbInstance returning undefined in the chrome tab before due to the wrong window context being selected, but it should be able to pass from the test setup to your application since they share a window. At least that is the pattern I am using to test a number of React + Firebase apps include Fireadmin (examples linked above).

**Comment by jwbaart** [comment]
Not sure what this exactly means. I currently execute the firebase.initializeApp twice(app module & cypres command) with the same config when in dev mode. Is this correct or should I only execute it once or use the result of firebase.initializeApp in the other location?

The window.fbInstance is only defined in the cypress window context, see below screenshot:
![image](https://user-images.githubusercontent.com/10973990/72638916-c4d49380-3964-11ea-898c-5f2d957fb7ee.png)

**Comment by prescottprue** [comment]
That is correct that it should be initialized both places, but within your application code you should load the existing Firebase instance from `window.fbInstance` if it is defined and only initialize if it is not defined

**Comment by jwbaart** [comment]
Chrome console:
context app: window.fbInstance -> undefined
context Cypress: window.fbInstance ->{firebase: {...}}

Debugging in the app also shows an undefined for the window.fbInstance.

> but it should be able to pass from the test setup to your application since they share a window.

Currently they aren't able to pass on the window.fbInstance in my setup and in your two examples(btw the second has an incorrect link, it links to the first example) they all expect a defined window.fbInstance.

I'm seeing the same behaviour in [this issue](https://github.com/prescottprue/cypress-firebase/issues/45). I'll try the sessionStorage workaround for now.

**Comment by prescottprue** [comment]
Not sure why I haven't experienced this in any of the projects I have been testing using these patterns. I wouldn't think it has to do with Angular, but I don't have any projects that use it that I am currently testing

Can you provide a full repo showing this issues so that I can debug further? Thanks for your patience - really want to get an answer to this one
